### ISSUE TITLE
transform/schema.yml has no version

### ISSUE THREAD

**Issue by arneeder** [dbt-labs/facebook-ads-bigquery#2]
as there is no version in the .yml getdbt fails to compile

**Comment by drewbanin** [comment]
hey @arneeder  - I just added a note to the README for this package indicating that it is deprecated! There's another facebook-ads package (https://github.com/fishtown-analytics/facebook-ads) that might be worth checking out, but I'm unsure if it supports BigQuery off the top of my head.

Please do feel free to poke around in this repo and copy out any files that you'd find useful though. Thanks, and sorry about that!

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
